version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    ports:
      - "6379:6379"

  api:
    build:
      context: ./api
      dockerfile: ../Dockerfile.api
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis

  worker:
    build:
      context: ./worker
      dockerfile: ../Dockerfile.worker
    depends_on:
      - mongo
      - redis

  webhook:
    build:
      context: ./webhook
      dockerfile: ../Dockerfile.webhook
    ports:
      - "4000:4000"
    depends_on:
      - mongo

  vendor-mocks:
    build:
      context: ./vendor-mocks
      dockerfile: ../Dockerfile.vendor
    ports:
      - "5000:5000"

volumes:
  mongo_data: